[versions]
kotlin = "2.0.20"
shadow = "8.3.3"
sonatype-central-portal-publisher = "1.2.3"
waterdog = "2.0.3-SNAPSHOT"

[libraries]
kotlin-jvm = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
waterdog = { module = "dev.waterdog.waterdogpe:waterdog", version.ref = "waterdog"}

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
sonatype-central-portal-publisher = { id = "net.thebugmc.gradle.sonatype-central-portal-publisher", version.ref = "sonatype-central-portal-publisher" }